name: Deploy pre TMA with Mate

on:
  push:
    branches:
      - pre

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Audit sources
        run: yarn lint

      - name: Build application
        run: yarn build
        env:
          VITE_BASE_URL: https://ee1381e897.tapps.global/${{ github.ref_name }}/
          VITE_BASE_API_URL: ${{ secrets.VITE_BASE_API_URL }}
          VITE_TMA_LINK: ${{ secrets.VITE_TMA_LINK }}

      - uses: actions/upload-artifact@v4
        with:
          name: tma-artifact
          path: |
            ./
            !node_modules

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: tma-artifact

      - name: Deploy via Mate
        run: |
          npx @telegram-apps/mate@latest deploy upload \
          --dir dist \
          --token ${{ secrets.MATE_DEPLOY_TOKEN }} \
          --project ${{ secrets.MATE_PROJECT_ID }} \
          --tag ${{ github.ref_name }}
